module proc (
    input  logic [8:0] DIN,
    input  logic       Resetn,
    input  logic       Clock,
    input  logic       Run,
    output logic       Done,
    output logic [8:0] BusWires
);

    parameter logic [1:0] T0 = 2'b00, T1 = 2'b01, T2 = 2'b10, T3 = 2'b11;

    // ==========================================
    // TODO: declare variables 
    // ==========================================

    // FSM current state and next state
    logic [1:0] Tstep_Q, Tstep_D;

    // Instruction Register and decoded instruction fields
    logic [8:0] IR;        // Holds the current 9-bit instruction: III XXX YYY
    logic [2:0] I;         // Opcode field: IR[8:6]

    // One-hot register selects for Rx and Ry
    logic [7:0] Xreg;      // Decoded Rx field: IR[5:3]
    logic [7:0] Yreg;      // Decoded Ry field: IR[2:0]

    // General-purpose registers
    logic [8:0] R0, R1, R2, R3, R4, R5, R6, R7;

    // Internal processor registers
    logic [8:0] A;             // First ALU operand
    logic [8:0] G;             // Stores ALU result
    logic [8:0] ALU_result;    // Combinational output of the ALU

    // Control signals generated by the FSM
    logic [7:0] Rin;       // Load enables for R0-R7
    logic [7:0] Rout;      // Output enables from R0-R7 to the bus
    logic       Ain;       // Load enable for A
    logic       Gin;       // Load enable for G
    logic       IRin;      // Load enable for IR
    logic       DINout;    // Select DIN as bus source
    logic       Gout;      // Select G as bus source
    logic       AddSub;    // 0 = add, 1 = subtract

    // Loop variable for the ones instruction
    integer k;

    assign I = IR[8:6]; 

    dec3to8 decX (.W(IR[5:3]), .En(1'b1), .Y(Xreg));
    dec3to8 decY (.W(IR[2:0]), .En(1'b1), .Y(Yreg));

    // Control FSM state table
    always_comb begin
        case (Tstep_Q)
            T0: begin 
                if (!Run) Tstep_D = T0;
                else      Tstep_D = T1;
            end
            
            // ==========================================
            // TODO: Complete FSM implementation
            // ==========================================

            T1: begin
                // mv and mvi finish in T1.
                // ALU-based instructions continue to T2.
                case (I)
                    3'b000: Tstep_D = T0; // mv
                    3'b001: Tstep_D = T0; // mvi
                    3'b010: Tstep_D = T2; // add
                    3'b011: Tstep_D = T2; // sub
                    3'b100: Tstep_D = T2; // ones
                    3'b101: Tstep_D = T2; // specialMult
                    default: Tstep_D = T0;
                endcase
            end

            T2: begin
                // Multi-cycle instructions finish their ALU work in T2,
                // then write the result back in T3.
                case (I)
                    3'b010,
                    3'b011,
                    3'b100,
                    3'b101: Tstep_D = T3;
                    default: Tstep_D = T0;
                endcase
            end

            T3: begin
                // Final write-back step, then return to T0.
                Tstep_D = T0;
            end
            
            default: Tstep_D = T0;
        endcase
    end

    // Control FSM outputs
    always_comb begin
        // ==========================================
        // TODO: specify initial values 
        // ==========================================

        // Default values are required so that the combinational block
        // does not infer latches and no old control signal remains active.
        IRin   = 1'b0;
        Rin    = 8'b00000000;
        Rout   = 8'b00000000;
        Ain    = 1'b0;
        Gin    = 1'b0;
        DINout = 1'b0;
        Gout   = 1'b0;
        AddSub = 1'b0;
        Done   = 1'b0;

        case (Tstep_Q)
            T0: begin // Store DIN in IR in time step 0
                // T0 fetches the instruction from DIN into IR.
                IRin = 1'b1;
            end
            
            T1: begin // Define signals in time step 1
                case (I)
                    // ==========================================
                    // TODO: Complete instruction decoding for T1
                    // ==========================================

                    3'b000: begin
                        // mv Rx,Ry: Rx <- Ry
                        // Put Ry on the bus and load Rx from the bus.
                        Rout = Yreg;
                        Rin  = Xreg;
                        Done = 1'b1;
                    end

                    3'b001: begin
                        // mvi Rx,#D: Rx <- DIN
                        // The immediate value D is supplied on DIN after the instruction word.
                        DINout = 1'b1;
                        Rin    = Xreg;
                        Done   = 1'b1;
                    end

                    3'b010: begin
                        // add Rx,Ry step 1: A <- Rx
                        // Store the first operand in A.
                        Rout = Xreg;
                        Ain  = 1'b1;
                    end

                    3'b011: begin
                        // sub Rx,Ry step 1: A <- Rx
                        // Store the first operand in A.
                        Rout = Xreg;
                        Ain  = 1'b1;
                    end

                    3'b100: begin
                        // ones Rx,Ry step 1: A <- Rx
                        // The ALU will count the number of 1 bits in A in T2.
                        Rout = Xreg;
                        Ain  = 1'b1;
                    end

                    3'b101: begin
                        // specialMult Rx,Ry step 1: A <- Rx
                        // The ALU will compute A * 3.5 in T2.
                        Rout = Xreg;
                        Ain  = 1'b1;
                    end

                    default: begin
                        // Unknown instruction: finish safely.
                        Done = 1'b1;
                    end
                endcase
            end
            
            T2: begin // Define signals in time step 2
                case (I)
                    // ==========================================
                    // TODO: Complete instruction decoding for T2
                    // ==========================================

                    3'b010: begin
                        // add Rx,Ry step 2: G <- A + Ry
                        // Put Ry on the bus, ALU adds A + BusWires, and G stores the result.
                        Rout = Yreg;
                        Gin  = 1'b1;
                    end

                    3'b011: begin
                        // sub Rx,Ry step 2: G <- A - Ry
                        // Put Ry on the bus, ALU subtracts BusWires from A, and G stores the result.
                        Rout   = Yreg;
                        Gin    = 1'b1;
                        AddSub = 1'b1;
                    end

                    3'b100: begin
                        // ones Rx,Ry step 2: G <- count_ones(A)
                        // No second bus operand is needed.
                        Gin = 1'b1;
                    end

                    3'b101: begin
                        // specialMult Rx,Ry step 2: G <- A * 3.5
                        // No second bus operand is needed.
                        Gin = 1'b1;
                    end

                    default: begin
                        // No operation.
                    end
                endcase
            end
            
            T3: begin // Define signals in time step 3
                case (I)
                    // ==========================================
                    // TODO: Complete instruction decoding for T3
                    // ==========================================

                    3'b010: begin
                        // add Rx,Ry final step: Rx <- G
                        Gout = 1'b1;
                        Rin  = Xreg;
                        Done = 1'b1;
                    end

                    3'b011: begin
                        // sub Rx,Ry final step: Rx <- G
                        Gout = 1'b1;
                        Rin  = Xreg;
                        Done = 1'b1;
                    end

                    3'b100: begin
                        // ones Rx,Ry final step: Ry <- G
                        // The lab defines the destination of ones as the second register.
                        Gout = 1'b1;
                        Rin  = Yreg;
                        Done = 1'b1;
                    end

                    3'b101: begin
                        // specialMult Rx,Ry final step: Ry <- G
                        // The lab defines the destination of specialMult as the second register.
                        Gout = 1'b1;
                        Rin  = Yreg;
                        Done = 1'b1;
                    end

                    default: begin
                        Done = 1'b1;
                    end
                endcase
            end
            default: ;
        endcase
    end

    // Control FSM flip-flops
    always_ff @(posedge Clock or negedge Resetn) begin
        if (!Resetn) begin
            // ==========================================
            // TODO: Reset FSM FF implementation
            // ==========================================
            Tstep_Q <= T0;
        end else begin
            Tstep_Q <= Tstep_D;
        end
    end

    // Instantiations of registers
   
    regn #(.n(9)) reg_0 (.R(BusWires), .Rin(Rin[0]), .Clock(Clock), .Resetn(Resetn), .Q(R0));

    // ==========================================
    // TODO: Complete the proc implementation 
    //       based on the lab guidelines
    // ==========================================

    // General-purpose registers R1-R7.
    // R0 was already instantiated in the original student code above.
    regn #(.n(9)) reg_1 (.R(BusWires), .Rin(Rin[1]), .Clock(Clock), .Resetn(Resetn), .Q(R1));
    regn #(.n(9)) reg_2 (.R(BusWires), .Rin(Rin[2]), .Clock(Clock), .Resetn(Resetn), .Q(R2));
    regn #(.n(9)) reg_3 (.R(BusWires), .Rin(Rin[3]), .Clock(Clock), .Resetn(Resetn), .Q(R3));
    regn #(.n(9)) reg_4 (.R(BusWires), .Rin(Rin[4]), .Clock(Clock), .Resetn(Resetn), .Q(R4));
    regn #(.n(9)) reg_5 (.R(BusWires), .Rin(Rin[5]), .Clock(Clock), .Resetn(Resetn), .Q(R5));
    regn #(.n(9)) reg_6 (.R(BusWires), .Rin(Rin[6]), .Clock(Clock), .Resetn(Resetn), .Q(R6));
    regn #(.n(9)) reg_7 (.R(BusWires), .Rin(Rin[7]), .Clock(Clock), .Resetn(Resetn), .Q(R7));

    // A register: stores the first operand before an ALU operation.
    regn #(.n(9)) reg_A  (.R(BusWires),   .Rin(Ain),  .Clock(Clock), .Resetn(Resetn), .Q(A));

    // G register: stores the ALU output so it can be written back later.
    regn #(.n(9)) reg_G  (.R(ALU_result), .Rin(Gin),  .Clock(Clock), .Resetn(Resetn), .Q(G));

    // Instruction Register: loads directly from DIN, according to the schematic.
    regn #(.n(9)) reg_IR (.R(DIN),        .Rin(IRin), .Clock(Clock), .Resetn(Resetn), .Q(IR));

    // ==========================================
    // Bus multiplexer
    // ==========================================
    // Only one source is selected to drive the bus at a time.
    // DINout selects DIN, Gout selects G, and Rout selects one of R0-R7.
    always_comb begin
        BusWires = 9'b000000000;

        if (DINout) begin
            BusWires = DIN;
        end
        else if (Gout) begin
            BusWires = G;
        end
        else begin
            case (Rout)
                8'b00000001: BusWires = R0;
                8'b00000010: BusWires = R1;
                8'b00000100: BusWires = R2;
                8'b00001000: BusWires = R3;
                8'b00010000: BusWires = R4;
                8'b00100000: BusWires = R5;
                8'b01000000: BusWires = R6;
                8'b10000000: BusWires = R7;
                default:     BusWires = 9'b000000000;
            endcase
        end
    end

    // ==========================================
    // ALU implementation
    // ==========================================
    // The ALU uses A as the first operand.
    // For add/sub, the second operand is BusWires.
    // For ones/specialMult, the operation is performed on A only.
    always_comb begin
        ALU_result = 9'b000000000;

        case (I)
            3'b010: begin
                // add: A + BusWires
                ALU_result = A + BusWires;
            end

            3'b011: begin
                // sub: A - BusWires
                // AddSub is asserted in T2 for the sub instruction.
                if (AddSub)
                    ALU_result = A - BusWires;
                else
                    ALU_result = A + BusWires;
            end

            3'b100: begin
                // ones: count how many bits in A are equal to 1.
                // Example: A = 000110011 -> ALU_result = 000000100.
                // The for loop checks all 9 bits one by one and adds each bit to the result.
                ALU_result = 9'b000000000;
                for (k = 0; k < 9; k = k + 1) begin
                    ALU_result = ALU_result + A[k];
                end
            end

            3'b101: begin
                // specialMult: compute A * 3.5 without using a multiplier.
                // 3.5A = 2A + A + 0.5A.
                // Left shift by 1 gives 2A, right shift by 1 gives A/2.
                // The lab states this instruction only needs to work correctly for even Rx values.
                ALU_result = ($signed(A) <<< 1) + $signed(A) + ($signed(A) >>> 1);
            end

            default: begin
                ALU_result = 9'b000000000;
            end
        endcase
    end

endmodule